// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpcnVk42b0uqDuc_uhZRfoySFlVUMt08Q',
    appId: '1:251845330199:web:2ce93e3815bcf971902352',
    messagingSenderId: '251845330199',
    projectId: 'mynotes-flutter-test-99c83',
    authDomain: 'mynotes-flutter-test-99c83.firebaseapp.com',
    storageBucket: 'mynotes-flutter-test-99c83.firebasestorage.app',
    measurementId: 'G-T2NQYN48XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB09W7qf1pz8Jdc9pcUE2Ufa99HRHc3HjI',
    appId: '1:251845330199:android:af75fdd113ef0712902352',
    messagingSenderId: '251845330199',
    projectId: 'mynotes-flutter-test-99c83',
    storageBucket: 'mynotes-flutter-test-99c83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1ugPa136RJrSxBlbWFNatthLr0y-Gv6g',
    appId: '1:251845330199:ios:4529112322863063902352',
    messagingSenderId: '251845330199',
    projectId: 'mynotes-flutter-test-99c83',
    storageBucket: 'mynotes-flutter-test-99c83.firebasestorage.app',
    iosBundleId: 'com.example.mynote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1ugPa136RJrSxBlbWFNatthLr0y-Gv6g',
    appId: '1:251845330199:ios:4529112322863063902352',
    messagingSenderId: '251845330199',
    projectId: 'mynotes-flutter-test-99c83',
    storageBucket: 'mynotes-flutter-test-99c83.firebasestorage.app',
    iosBundleId: 'com.example.mynote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpcnVk42b0uqDuc_uhZRfoySFlVUMt08Q',
    appId: '1:251845330199:web:90ca2212f6d0555f902352',
    messagingSenderId: '251845330199',
    projectId: 'mynotes-flutter-test-99c83',
    authDomain: 'mynotes-flutter-test-99c83.firebaseapp.com',
    storageBucket: 'mynotes-flutter-test-99c83.firebasestorage.app',
    measurementId: 'G-5NCKLS1SPK',
  );
}
